package cli

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/dantedelordran/maniplacer/internal/utils"
	"github.com/spf13/cobra"
)

var pruneCmd = &cobra.Command{
	Use:   "prune",
	Short: "Removes every created manifest given a namespace",
	Long: `The prune command deletes all manifests generated by Maniplacer under a specific namespace.

By default, it targets the 'default' namespace, but you can override this with the --namespace (or -n) flag. You must also specify the target repository with the --repo (or -r) flag.

Before deletion, the command ensures:
- You are inside a valid Maniplacer project.
- The manifests directory for the namespace exists and is not empty.
- You explicitly confirm the deletion to prevent accidental data loss.

This command is especially useful for:
- Cleaning up old or unused manifests before generating fresh ones.
- Resetting environments between deployments.
- Freeing up space and avoiding clutter in your project.

Example usage:
  maniplacer prune
  maniplacer prune -n staging -r myrepo

If confirmed, this will remove all manifests inside the 'staging' namespace of the 'myrepo' repository.`,
	Args: cobra.MaximumNArgs(0),
	RunE: func(cmd *cobra.Command, args []string) error {
		logger := utils.LoggerFromContext(cmd.Context())

		if !utils.IsValidProject() {
			return fmt.Errorf("current directory is not a valid Maniplacer project")
		}

		confirmed := utils.ConfirmMessage("Confirm from Deleting manifests?")

		namespace, err := cmd.Flags().GetString("namespace")
		if err != nil {
			logger.Debug("could not parse namespace flag, using default", "error", err)
			namespace = utils.DefaultNamespace
		}

		// Validate namespace
		if err := utils.ValidateNamespace(namespace); err != nil {
			return fmt.Errorf("invalid namespace: %w", err)
		}

		repo, err := cmd.Flags().GetString("repo")
		if err != nil {
			return fmt.Errorf("could not get repo flag: %w", err)
		}

		if repo == "" {
			return fmt.Errorf("repository name is required (use --repo flag)")
		}

		// Validate repo name and check for path traversal
		if err := utils.ValidateRepoName(repo); err != nil {
			return fmt.Errorf("invalid repository name: %w", err)
		}
		if err := utils.ValidateSafePath(repo); err != nil {
			return err
		}

		currentDir, err := os.Getwd()
		if err != nil {
			return fmt.Errorf("could not get current directory: %w", err)
		}

		currentDir = filepath.Join(currentDir, repo, "manifests", namespace)

		_, err = os.Stat(currentDir)
		if err != nil {
			return fmt.Errorf("manifest directory does not exist: %w", err)
		}

		files, err := os.ReadDir(currentDir)
		if err != nil {
			return fmt.Errorf("could not read manifests directory: %w", err)
		}

		if len(files) == 0 {
			fmt.Printf("No manifests in %s namespace\n", namespace)
			return nil
		}

		if !confirmed {
			fmt.Printf("No manifest will be deleted :P\n")
			return nil
		}

		logger.Info("deleting manifests", "namespace", namespace, "count", len(files))
		fmt.Printf("Deleting manifests in %s namespace...\n", namespace)

		for _, file := range files {
			filePath := filepath.Join(currentDir, file.Name())
			if err = os.RemoveAll(filePath); err != nil {
				logger.Warn("could not delete file, skipping", "file", file.Name(), "error", err)
				fmt.Printf("Could not delete %s due to %s, skipping...\n", file.Name(), err)
				continue
			}
			logger.Info("file deleted", "file", file.Name())
			fmt.Printf("Successfully deleted %s\n", file.Name())
		}

		logger.Info("prune complete", "namespace", namespace)
		return nil
	},
}

func init() {
	rootCmd.AddCommand(pruneCmd)
	pruneCmd.Flags().StringP("namespace", "n", utils.DefaultNamespace, "Namespace for pruning manifests")
	pruneCmd.Flags().StringP("repo", "r", "", "Repo name")
}
