package cli

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/dantedelordran/maniplacer/internal/utils"
	"github.com/spf13/cobra"
)

var pruneCmd = &cobra.Command{
	Use:   "prune",
	Short: "Removes every created manifest given a namespace",
	Long: `The prune command deletes all manifests generated by Maniplacer under a specific namespace.

By default, it targets the 'default' namespace, but you can override this with the --namespace (or -n) flag. You must also specify the target repository with the --repo (or -r) flag.

Before deletion, the command ensures:
- You are inside a valid Maniplacer project.
- The manifests directory for the namespace exists and is not empty.
- You explicitly confirm the deletion to prevent accidental data loss.

This command is especially useful for:
- Cleaning up old or unused manifests before generating fresh ones.
- Resetting environments between deployments.
- Freeing up space and avoiding clutter in your project.

Example usage:
  maniplacer prune
  maniplacer prune -n staging -r myrepo

If confirmed, this will remove all manifests inside the 'staging' namespace of the 'myrepo' repository.`,
	Args: cobra.MaximumNArgs(0),
	RunE: func(cmd *cobra.Command, args []string) error {
		logger := utils.LoggerFromContext(cmd.Context())

		target, err := resolveTarget(cmd)
		if err != nil {
			return err
		}

		manifestsDir := target.ManifestsDir()

		if _, err := os.Stat(manifestsDir); err != nil {
			return fmt.Errorf("manifest directory does not exist: %w", err)
		}

		files, err := os.ReadDir(manifestsDir)
		if err != nil {
			return fmt.Errorf("could not read manifests directory: %w", err)
		}

		if len(files) == 0 {
			fmt.Printf("No manifests in %s namespace\n", target.Namespace)
			return nil
		}

		// Only ask once there is actually something to delete
		if !utils.ConfirmMessage(fmt.Sprintf("Delete %d manifest(s) in the %s namespace?", len(files), target.Namespace)) {
			fmt.Printf("No manifest will be deleted :P\n")
			return nil
		}

		fmt.Printf("Deleting manifests in %s namespace...\n", target.Namespace)

		for _, file := range files {
			filePath := filepath.Join(manifestsDir, file.Name())
			if err = os.RemoveAll(filePath); err != nil {
				logger.Warn("could not delete file, skipping", "file", file.Name(), "error", err)
				fmt.Printf("Could not delete %s due to %s, skipping...\n", file.Name(), err)
				continue
			}
			fmt.Printf("Successfully deleted %s\n", file.Name())
		}

		logger.Debug("prune complete", "namespace", target.Namespace)
		return nil
	},
}

func init() {
	rootCmd.AddCommand(pruneCmd)
	addRepoNamespaceFlags(pruneCmd, "Namespace for pruning manifests")
}
